# Generated by Django 2.2 on 2020-03-26 17:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import martor.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField()),
                ('color', models.CharField(max_length=15)),
                ('desc', models.TextField(blank=True)),
                ('order', models.IntegerField(blank=True, default=1)),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField()),
                ('meta_title', models.CharField(blank=True, max_length=100)),
                ('desc', models.TextField(blank=True)),
                ('banner', models.ImageField(blank=True, upload_to='post/banner/%Y/%m/%d/')),
                ('thumb', models.ImageField(blank=True, upload_to='post/thumb/%Y/%m/%d/')),
                ('content', martor.models.MartorField()),
                ('meta_tags', models.TextField(blank=True)),
                ('order', models.IntegerField(blank=True, default=1)),
                ('published_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='blog.Category')),
            ],
        ),
    ]
