# Generated by Django 2.2 on 2020-03-25 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeslider',
            name='align',
            field=models.CharField(choices=[('left', 'left'), ('center', 'center'), ('right', 'right')], default='left', max_length=10),
        ),
    ]
