# Generated by Django 2.2 on 2020-03-25 12:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('slug', models.SlugField()),
                ('svg', models.FileField(upload_to='skill/svg/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(['svg'])])),
                ('percent', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)])),
                ('color', models.CharField(max_length=15)),
                ('order', models.IntegerField(blank=True, default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Showcase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField()),
                ('img', models.ImageField(upload_to='showcase/img/%Y/%m/%d/')),
                ('desc', models.TextField(blank=True)),
                ('link_to', models.CharField(max_length=100)),
                ('order', models.IntegerField(blank=True, default=1)),
                ('published_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('skills', models.ManyToManyField(related_name='showcases', to='skill.Skill')),
            ],
        ),
    ]
